# Generated by Django 4.2.9 on 2024-01-27 13:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=50)),
                ('link', models.URLField(max_length=400)),
            ],
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=70)),
                ('description', models.TextField()),
                ('link', models.URLField(max_length=400)),
                ('verified', models.BooleanField()),
                ('id_author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='author_courses', to='api.author')),
            ],
        ),
        migrations.CreateModel(
            name='Platform',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=15)),
                ('description', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='UserCourse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_courses', models.ManyToManyField(related_name='course_users', to='api.course')),
                ('id_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_courses', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Reviews',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.IntegerField()),
                ('text_review', models.TextField(blank=True, null=True)),
                ('creation_date', models.DateTimeField()),
                ('id_course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='course_reviews', to='api.course')),
                ('id_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_rewiews', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='course',
            name='id_platform',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='platform_courses', to='api.platform'),
        ),
        migrations.AddField(
            model_name='course',
            name='id_publisher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_published', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='course',
            name='tags',
            field=models.ManyToManyField(related_name='course_tags', to='api.tag'),
        ),
        migrations.CreateModel(
            name='Commentary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creation_date', models.DateTimeField()),
                ('commentary_text', models.TextField()),
                ('likes', models.IntegerField(default=0)),
                ('id_course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='course_commentaries', to='api.course')),
                ('id_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_commentaries', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
