# Generated by Django 4.2.9 on 2024-01-28 02:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_rename_reviews_review'),
    ]

    operations = [
        migrations.RenameField(
            model_name='commentary',
            old_name='id_course',
            new_name='course',
        ),
        migrations.RenameField(
            model_name='commentary',
            old_name='id_user',
            new_name='user',
        ),
        migrations.RenameField(
            model_name='course',
            old_name='id_author',
            new_name='author',
        ),
        migrations.RenameField(
            model_name='course',
            old_name='id_platform',
            new_name='platform',
        ),
        migrations.RenameField(
            model_name='course',
            old_name='id_publisher',
            new_name='publisher',
        ),
        migrations.RenameField(
            model_name='review',
            old_name='id_course',
            new_name='course',
        ),
        migrations.RenameField(
            model_name='review',
            old_name='id_user',
            new_name='user',
        ),
        migrations.RenameField(
            model_name='usercourse',
            old_name='id_courses',
            new_name='courses',
        ),
        migrations.RenameField(
            model_name='usercourse',
            old_name='id_user',
            new_name='user',
        ),
        migrations.AlterField(
            model_name='tag',
            name='description',
            field=models.CharField(max_length=600),
        ),
    ]
