# Generated by Django 4.2.9 on 2024-01-31 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_rename_id_course_commentary_course_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='creation_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
