# Generated by Django 4.2.9 on 2024-01-31 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_review_creation_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commentary',
            name='creation_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
