# Generated by Django 4.2.9 on 2024-01-31 20:00

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('api', '0005_alter_commentary_creation_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='review',
            name='course',
        ),
        migrations.AddField(
            model_name='course',
            name='rewies',
            field=models.ManyToManyField(related_name='course_reviews', to='api.review'),
        ),
        migrations.AddField(
            model_name='course',
            name='users',
            field=models.ManyToManyField(related_name='course_users', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='usercourse',
            name='courses',
            field=models.ManyToManyField(related_name='course_users_1', to='api.course'),
        ),
    ]
