# Generated by Django 4.2.9 on 2024-01-31 20:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_rename_rewies_course_reviews'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='reviews',
        ),
        migrations.AddField(
            model_name='review',
            name='course',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='course_reviews', to='api.course'),
            preserve_default=False,
        ),
    ]
