# Generated by Django 4.2.9 on 2024-01-31 21:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_comment_delete_commentary'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='id_course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='api.course'),
        ),
    ]
