# Generated by Django 4.2.9 on 2024-04-25 23:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0016_remove_course_users_course_paid_course_rating_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='cost',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
