# Generated by Django 4.2.9 on 2024-05-09 18:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0019_searchwords_course_search_words'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='SearchWords',
            new_name='SearchWord',
        ),
    ]
