# Generated by Django 4.2.9 on 2024-05-10 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0020_rename_searchwords_searchword'),
    ]

    operations = [
        migrations.AddField(
            model_name='searchword',
            name='weight',
            field=models.IntegerField(default=0),
        ),
    ]
