# Generated by Django 4.2.9 on 2024-05-10 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0022_alter_course_paid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='paid',
            field=models.BooleanField(default=False),
        ),
    ]
