# Generated by Django 4.2.9 on 2024-05-11 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0023_alter_course_paid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usercourse',
            name='courses',
            field=models.ManyToManyField(blank=True, related_name='course_users', to='api.course'),
        ),
    ]
