# Generated by Django 4.2.9 on 2024-05-12 09:07

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('api', '0025_course_users'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='users',
            field=models.ManyToManyField(blank=True, related_name='course_users', to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='UserCourse',
        ),
    ]
