# Generated by Django 4.2.9 on 2024-05-13 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0027_newspost'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newspost',
            name='post_text',
            field=models.TextField(null=True),
        ),
    ]
