# Generated by Django 4.2.9 on 2024-05-13 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0028_alter_newspost_post_text'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newspost',
            name='post_text',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='reports',
            name='report_text',
            field=models.TextField(),
        ),
    ]
