# Generated by Django 4.2.9 on 2024-05-13 23:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0030_rename_reports_report'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='report',
            name='user',
        ),
        migrations.AddField(
            model_name='report',
            name='header',
            field=models.CharField(default='empty', max_length=70),
            preserve_default=False,
        ),
    ]
