# Generated by Django 4.2.9 on 2024-05-13 23:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0031_remove_report_user_report_header'),
    ]

    operations = [
        migrations.AddField(
            model_name='newspost',
            name='header',
            field=models.CharField(default='empty', max_length=70),
            preserve_default=False,
        ),
    ]
