# Generated by Django 4.2.9 on 2024-05-14 18:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0033_coopproposal'),
    ]

    operations = [
        migrations.RenameField(
            model_name='coopproposal',
            old_name='proposal',
            new_name='proposal_text',
        ),
    ]
