# Generated by Django 4.2.9 on 2024-05-14 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0034_rename_proposal_coopproposal_proposal_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='coopproposal',
            name='status',
            field=models.CharField(default='new', max_length=20),
        ),
    ]
