# Generated by Django 4.2.9 on 2024-05-14 18:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0035_coopproposal_status'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CoopProposal',
        ),
    ]
