# Generated by Django 4.2.9 on 2024-05-21 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0038_alter_course_tags'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='cost',
        ),
        migrations.AddField(
            model_name='course',
            name='price',
            field=models.IntegerField(default=0),
        ),
    ]
